services:
  - type: web
    name: yuksalishfikrbot
    env: python
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7739117900:AAHjKGVqeJR2PToZ_1p2mb9ndVuR-nMr-xY
      - key: ADMIN_IDS
        value: 123456789,987654321
